export const ADD_INGREDIENT_TO_CART = 'ADD_INGREDIENT_TO_CART';
export const ADD_BUN_TO_CART = 'ADD_BUN_TO_CART';
export const RESET_INITIAL_STATE = 'RESET_INITIAL_STATE';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';